<script>
	import Navbar from '../../../../components/Navbar.svelte';
</script>

<!-- Digisin Navbar -->
<Navbar />

<div class="container mx-auto px-4 py-8 sm:px-6 md:px-8">
	<!-- Digisin Search -->
	<div>
		<h1
			class="text-mainColor2 font-bold text-4xl max-w-2xl md:text-5xl xl:text-6xl tracking-tight leading-none mb-4"
		>
			Add Display
		</h1>
		<p class="text-black font-light text-xl">Create your display here</p>
	</div>

	<form>
		<div class="grid gap-6 mb-6 md:grid-cols-2">
			<div>
				<label for="first_name" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
					>ID</label
				>
				<input
					type="text"
					id="first_name"
					class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
					placeholder="123456789"
					required
				/>
				<p class="mt-2 text-sm text-black dark:text-green-500">
					ID of your digital sginage display (automatically generated by the system)
				</p>
			</div>
			<div>
				<label for="last_name" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
					>Name</label
				>
				<input
					type="text"
					id="last_name"
					class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
					placeholder="Display Name *"
					required
				/>
				<p class="mt-2 text-sm text-black dark:text-green-500">
					Name of your digital signage display (you can customize it)
				</p>
			</div>
			<div>
				<label for="company" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
					>Link</label
				>
				<input
					type="text"
					id="company"
					class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
					placeholder="http://127.0.0.1:5173/Link *"
					required
				/>
				<p class="mt-2 text-sm text-black dark:text-green-500">
					Link of your digital signage display (paste it into your television)
				</p>
			</div>
            <div>
				<label for="company" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
					>Status</label
				>
				<input
					type="text"
					id="company"
					class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
					placeholder="active/deactive"
					required
				/>
				<p class="mt-2 text-sm text-black dark:text-green-500">
					Status of your digital signage display
				</p>
			</div>
            <div>
				<label for="company" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
					>Select Template</label
				>
				<input
					type="text"
					id="company"
					class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
					placeholder="horizontal/vertical"
					required
				/>
				<p class="mt-2 text-sm text-black dark:text-green-500">
					Template of your digital signage (there are horizontal and vertical templates)
				</p>
			</div>
			<div>
				<label for="website" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
					>Log Edit</label
				>
				<input
					type="text"
					id="website"
					class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
					placeholder="Last edit was second ago"
					required
				/>
				<p class="mt-2 text-sm text-black dark:text-green-500">
					History of your digital signage display
				</p>
			</div>
		</div>
        
		<button
			type="submit"
			class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
			>Create</button
		>
	</form>
</div>
