<script>
	import Navbar from '../../../../components/Navbar.svelte';

	function deleteDisplays(){
		
	}

	let forms = [{}];

	function addForm() {
		forms = [...forms, {}];
	}

	function removeForm(index) {
		forms = forms.filter((_, i) => i !== index);
	}
</script>

<!-- Digisin Navbar -->
<Navbar />

<div class="container mx-auto px-4 py-8 sm:px-6 md:px-8">
	<!-- Digisin Search -->
	<div>
		<h1
			class="text-mainColor2 font-bold text-4xl max-w-2xl md:text-5xl xl:text-6xl tracking-tight leading-none mb-4"
		>
			Customize Display
		</h1>
		<p class="text-black font-light text-xl">Create your display here</p>
	</div>

	<form>
		<div class="grid gap-6 mb-6 md:grid-cols-2">
			<div>
				<label for="first_name" class="block mb-2 text-sm font-medium text-gray-900">ID</label>
				<input
					type="text"
					id="first_name"
					class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5"
					placeholder="123456789"
					required
				/>
				<p class="mt-2 text-sm text-black">
					ID of your digital sginage display (automatically generated by the system)
				</p>
			</div>
			<div>
				<label for="last_name" class="block mb-2 text-sm font-medium text-gray-900">Name</label>
				<input
					type="text"
					id="last_name"
					class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5"
					placeholder="Display Name *"
					required
				/>
				<p class="mt-2 text-sm text-black">
					Name of your digital signage display (you can customize it)
				</p>
			</div>
			<div>
				<label for="company" class="block mb-2 text-sm font-medium text-gray-900">Link</label>
				<input
					type="text"
					id="company"
					class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5"
					placeholder="http://127.0.0.1:5173/Link *"
					required
				/>
				<p class="mt-2 text-sm text-black">
					Link of your digital signage display (paste it into your television)
				</p>
			</div>
			<div>
				<label for="company" class="block mb-2 text-sm font-medium text-gray-900">Status</label>
				<input
					type="text"
					id="company"
					class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5"
					placeholder="active/deactive"
					required
				/>
				<p class="mt-2 text-sm text-black">Status of your digital signage display</p>
			</div>

			<div>
				<label for="company" class="block mb-2 text-sm font-medium text-gray-900"
					>Select Template</label
				>
				<input
					type="text"
					id="company"
					class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5"
					placeholder="horizontal/vertical"
					required
				/>
				<p class="mt-2 text-sm text-black">
					Template of your digital signage (there are horizontal and vertical templates)
				</p>
			</div>
			<div>
				<label for="website" class="block mb-2 text-sm font-medium text-gray-900">Log Edit</label>
				<input
					type="text"
					id="website"
					class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5"
					placeholder="Last edit was second ago"
					required
				/>
				<p class="mt-2 text-sm text-black">History of your digital signage display</p>
			</div>
		</div>

		<!-- Display Preview -->
		<img
			class="w-full h-full object-cover rounded-[10px]"
			src="http://via.placeholder.com/1920x1080"
			alt="adv"
		/>

		<!-- Digisin Queue Video -->
		<div>
			<p
				class="text-mainColor2 font-bold text-2xl md:text-2xl xl:text-4xl tracking-tight leading-none mb-4"
			>
				Media
			</p>

			<!-- Queue Form -->
			{#each forms as _, index (index)}
				<div class="flex items-center mb-2" key={index}>
					<input
						type="text"
						class="w-full border rounded p-2 mr-2"
						placeholder="https://www.youtube.com/embed/YOUTUBE-ID-HERE?autoplay=1&loop=1"
					/>
					<button
						class="bg-red-500 text-white py-2 px-3 rounded hover:bg-red-600"
						on:click={() => removeForm(index)}>Remove</button
					>
				</div>
			{/each}
		</div>

		<!-- Customize Display Action Control -->
		<div class="flex flex-col justify-end sm:flex-row space-y-2 sm:space-y-0 sm:space-x-2">
			<button
				class="w-full sm:w-auto bg-mainColor1 text-black text-center border border-mainColor2 py-2 px-4 rounded hover:bg-red-600"
				on:click={deleteDisplays}
				>Delete Dispays
			</button>

			<button
				class="w-full sm:w-auto bg-mainColor1 text-black text-center border border-mainColor2 py-2 px-4 rounded hover:bg-mainColor2"
				on:click={addForm}
				>Add Form
			</button>

			<a
				class="w-full sm:w-auto bg-mainColor1 text-black text-center border border-mainColor2 py-2 px-4 rounded hover:bg-mainColor2"
				href="/account/displays"
				>Cancel
			</a>

			<button
				type="submit"
				class="w-full sm:w-auto bg-mainColor1 text-black text-center border border-mainColor2 py-2 px-4 rounded hover:bg-mainColor2"
				>Update</button
			>
		</div>
	</form>
</div>
